###

# Add a new room
# curl -i -X POST localhost:8080/api/room -H 'Content-Type: application/json' -d '{"number":"0815","name":"little tiny room"}'
POST localhost:8080/api/room
Content-Type: application/json

{
  "number": "0815",
  "name": "little tiny room"
}

###

# Get a room by id
# curl -i -X GET localhost:8080/api/room/0815 -H 'Content-Type: application/json'
GET localhost:8080/api/room/0815
Content-Type: application/json

###


